### ISSUE TITLE
Does it support deadletterqueue?

### ISSUE THREAD

**Issue by plainfatboy** [Aiven-Open/opensearch-connector-for-apache-kafka#196]
I encounter this error

```[2023-04-27 05:41:58,858] ERROR [OpenSearchSinkKubeAudit|task-0] Failed to bulk processing after total of 1 attempt(s) (io.aiven.kafka.connect.opensearch.RetryUtil:136)
org.apache.kafka.connect.errors.ConnectException: Bulk request failed: OpenSearchException[OpenSearch exception [type=mapper_parsing_exception, reason=failed to parse]]; nested: OpenSearchException[OpenSearch exception [type=array_index_out_of_bounds_exception, reason=Index -1 out of bounds for length 0]];
	at io.aiven.kafka.connect.opensearch.BulkProcessor$BulkTask.handleMalformedDoc(BulkProcessor.java:456)
	at io.aiven.kafka.connect.opensearch.BulkProcessor$BulkTask.lambda$execute$0(BulkProcessor.java:380)
	at io.aiven.kafka.connect.opensearch.RetryUtil.callWithRetry(RetryUtil.java:119)
	at io.aiven.kafka.connect.opensearch.BulkProcessor$BulkTask.execute(BulkProcessor.java:367)
	at io.aiven.kafka.connect.opensearch.BulkProcessor$BulkTask.call(BulkProcessor.java:356)
	at io.aiven.kafka.connect.opensearch.BulkProcessor$BulkTask.call(BulkProcessor.java:337)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

I try to use deadletterqueue settings from https://www.confluent.io/blog/kafka-connect-deep-dive-error-handling-dead-letter-queues/.

However, it does not work. Would it be possible for someone to recommend a way to find out which message cause the above error.

Thank you very much for your support.

**Comment by willyborankin** [comment]
Hi @plainfatboy it supports dead letter queue but latest release no.
