### ISSUE TITLE
Plugin not added to kafka connect

### ISSUE THREAD

**Issue by mort1i** [Aiven-Open/opensearch-connector-for-apache-kafka#267]
I have an issue with this connector and that it does not load into kafka-connect and therefore cannot be used.

I am getting this error message in the logs:
`[2024-02-01 15:08:30,847] ERROR Failed to create connector for /opt/kafka-connect/es-sink.properties (org.apache.kafka.connect.cli.ConnectStandalone:74)
[2024-02-01 15:08:30,847] ERROR Stopping after connector error (org.apache.kafka.connect.cli.ConnectStandalone:84)
java.util.concurrent.ExecutionException: org.apache.kafka.connect.errors.ConnectException: Failed to find any class that implements Connector and which name matches io.aiven.kafka.connect.opensearch.OpensearchSinkConnector, available connectors are: PluginDesc{klass=class io.confluent.connect.elasticsearch.ElasticsearchSinkConnector, name='io.confluent.connect.elasticsearch.ElasticsearchSinkConnector', version='14.0.10', encodedVersion=14.0.10, type=sink, typeName='sink', location='file:/opt/kafka-connect/plugins/confluentinc-kafka-connect-elasticsearch-14.0.10/'}, PluginDesc{klass=class org.apache.kafka.connect.mirror.MirrorCheckpointConnector, name='org.apache.kafka.connect.mirror.MirrorCheckpointConnector', version='3.5.1', encodedVersion=3.5.1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.mirror.MirrorHeartbeatConnector, name='org.apache.kafka.connect.mirror.MirrorHeartbeatConnector', version='3.5.1', encodedVersion=3.5.1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.mirror.MirrorSourceConnector, name='org.apache.kafka.connect.mirror.MirrorSourceConnector', version='3.5.1', encodedVersion=3.5.1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.MockSinkConnector, name='org.apache.kafka.connect.tools.MockSinkConnector', version='3.5.1', encodedVersion=3.5.1, type=sink, typeName='sink', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.MockSourceConnector, name='org.apache.kafka.connect.tools.MockSourceConnector', version='3.5.1', encodedVersion=3.5.1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.SchemaSourceConnector, name='org.apache.kafka.connect.tools.SchemaSourceConnector', version='3.5.1', encodedVersion=3.5.1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.VerifiableSinkConnector, name='org.apache.kafka.connect.tools.VerifiableSinkConnector', version='3.5.1', encodedVersion=3.5.1, type=sink, typeName='sink', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.VerifiableSourceConnector, name='org.apache.kafka.connect.tools.VerifiableSourceConnector', version='3.5.1', encodedVersion=3.5.1, type=source, typeName='source', location='classpath'}
        at org.apache.kafka.connect.util.ConvertingFutureCallback.result(ConvertingFutureCallback.java:123)
        at org.apache.kafka.connect.util.ConvertingFutureCallback.get(ConvertingFutureCallback.java:107)
        at org.apache.kafka.connect.cli.ConnectStandalone.processExtraArgs(ConnectStandalone.java:81)
        at org.apache.kafka.connect.cli.AbstractConnectCli.startConnect(AbstractConnectCli.java:150)
        at org.apache.kafka.connect.cli.AbstractConnectCli.run(AbstractConnectCli.java:94)
        at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:112)
Caused by: org.apache.kafka.connect.errors.ConnectException: Failed to find any class that implements Connector and which name matches io.aiven.kafka.connect.opensearch.OpensearchSinkConnector, available connectors are: PluginDesc{klass=class io.confluent.connect.elasticsearch.ElasticsearchSinkConnector, name='io.confluent.connect.elasticsearch.ElasticsearchSinkConnector', version='14.0.10', encodedVersion=14.0.10, type=sink, typeName='sink', location='file:/opt/kafka-connect/plugins/confluentinc-kafka-connect-elasticsearch-14.0.10/'}, PluginDesc{klass=class org.apache.kafka.connect.mirror.MirrorCheckpointConnector, name='org.apache.kafka.connect.mirror.MirrorCheckpointConnector', version='3.5.1', encodedVersion=3.5.1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.mirror.MirrorHeartbeatConnector, name='org.apache.kafka.connect.mirror.MirrorHeartbeatConnector', version='3.5.1', encodedVersion=3.5.1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.mirror.MirrorSourceConnector, name='org.apache.kafka.connect.mirror.MirrorSourceConnector', version='3.5.1', encodedVersion=3.5.1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.MockSinkConnector, name='org.apache.kafka.connect.tools.MockSinkConnector', version='3.5.1', encodedVersion=3.5.1, type=sink, typeName='sink', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.MockSourceConnector, name='org.apache.kafka.connect.tools.MockSourceConnector', version='3.5.1', encodedVersion=3.5.1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.SchemaSourceConnector, name='org.apache.kafka.connect.tools.SchemaSourceConnector', version='3.5.1', encodedVersion=3.5.1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.VerifiableSinkConnector, name='org.apache.kafka.connect.tools.VerifiableSinkConnector', version='3.5.1', encodedVersion=3.5.1, type=sink, typeName='sink', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.VerifiableSourceConnector, name='org.apache.kafka.connect.tools.VerifiableSourceConnector', version='3.5.1', encodedVersion=3.5.1, type=source, typeName='source', location='classpath'}
        at org.apache.kafka.connect.runtime.isolation.Plugins.connectorClass(Plugins.java:253)
        at org.apache.kafka.connect.runtime.isolation.Plugins.newConnector(Plugins.java:224)
        at org.apache.kafka.connect.runtime.AbstractHerder.lambda$getConnector$6(AbstractHerder.java:702)
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
        at org.apache.kafka.connect.runtime.AbstractHerder.getConnector(AbstractHerder.java:702)
        at org.apache.kafka.connect.runtime.AbstractHerder.validateConnectorConfig(AbstractHerder.java:470)
        at org.apache.kafka.connect.runtime.AbstractHerder.lambda$validateConnectorConfig$2(AbstractHerder.java:390)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)`

The connector was extracted to "/opt/kafka-connect/plugins/opensearch-connector-for-apache-kafka-3.1.1/" and my "plugin.path" is set to "/opt/kafka-connect/plugins/".

In the logs I can see that my Elasticsearch Sink is loaded, but no plugin is loaded from the Opensearch Connector:
`[2024-02-01 15:08:27,607] INFO Loading plugin from: /opt/kafka-connect/plugins/confluentinc-kafka-connect-elasticsearch-14.0.10 (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:275)
[2024-02-01 15:08:28,623] INFO Registered loader: PluginClassLoader{pluginLocation=file:/opt/kafka-connect/plugins/confluentinc-kafka-connect-elasticsearch-14.0.10/} (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:297)
[2024-02-01 15:08:28,623] INFO Added plugin 'io.confluent.connect.elasticsearch.ElasticsearchSinkConnector' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:230)
...
[2024-02-01 15:08:28,624] INFO Loading plugin from: /opt/kafka-connect/plugins/opensearch-connector-for-apache-kafka-3.1.1 (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:275)
[2024-02-01 15:08:29,344] INFO Registered loader: PluginClassLoader{pluginLocation=file:/opt/kafka-connect/plugins/opensearch-connector-for-apache-kafka-3.1.1/} (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:297)
[2024-02-01 15:08:29,938] INFO Registered loader: sun.misc.Launcher$AppClassLoader@135fbaa4 (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:297)
[2024-02-01 15:08:29,939] INFO Added plugin 'org.apache.kafka.connect.tools.VerifiableSinkConnector' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:230)
...
`

Environment is CentOS Stream 9, java openjdk version "1.8.0_362", kafka version 3.5.1

**Comment by mort1i** [comment]
Closing this, seems to be solved with java 11
