### ISSUE TITLE
io.aiven.kafka.connect.opensearch.spi.ConfigDefContributor: io.aiven.kafka.connect.opensearch.OpensearchBasicAuthConfigurator Unable to get public no-arg

### ISSUE THREAD

**Issue by mtedge04** [Aiven-Open/opensearch-connector-for-apache-kafka#312]
I am seeing the following error using this connect config

name=opensearch-sink
connector.class=io.aiven.kafka.connect.opensearch.OpensearchSinkConnector
tasks.max=1
topics=test-opensearch-sink
key.ignore=true
connection.url=http://192.168.1.235:9200
type.name=kafka-connect
connection.username=user
connection.password=user
ssl_certificate_verification=false

[2024-09-19 23:12:47,437] INFO Kafka Connect started (org.apache.kafka.connect.runtime.Connect:57)
[2024-09-19 23:12:47,532] ERROR Failed to create connector for config/opensearch.properties (org.apache.kafka.connect.cli.ConnectStandalone:85)
[2024-09-19 23:12:47,534] ERROR Stopping after connector error (org.apache.kafka.connect.cli.ConnectStandalone:96)
java.util.concurrent.ExecutionException: java.util.ServiceConfigurationError: io.aiven.kafka.connect.opensearch.spi.ConfigDefContributor: io.aiven.kafka.connect.opensearch.OpensearchBasicAuthConfigurator Unable to get public no-arg constructor
	at org.apache.kafka.connect.util.ConvertingFutureCallback.result(ConvertingFutureCallback.java:135)
	at org.apache.kafka.connect.util.ConvertingFutureCallback.get(ConvertingFutureCallback.java:108)
	at org.apache.kafka.connect.cli.ConnectStandalone.processExtraArgs(ConnectStandalone.java:93)
	at org.apache.kafka.connect.cli.AbstractConnectCli.startConnect(AbstractConnectCli.java:150)
	at org.apache.kafka.connect.cli.AbstractConnectCli.run(AbstractConnectCli.java:94)
	at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:182)

**Comment by srolija** [comment]
Not sure if of any help to you, but it might help out someone else later on. 

In our standalone Kafka Connect worker config we had we setting `plugin.path=./plugins` and unzipped all the jars into `./plugins/*`. We then spent 2 hours on the same issue, but as soon as we put it into `./plugins/opensearch/*` it started to work. It is not folder specific (any subfolder works). So for some reason you can't put them into top level path.

**Comment by eric-almadova-gemini** [comment]
What `srolija` suggested worked for me. I was doing the same thing lol.

**Comment by willyborankin** [comment]
It is related to the Kafka Connect documentation on how to set up a connector.
